version: '3.8'

services:
  db:
    image: postgres:13
    container_name: ce_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo123
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:14.0
    container_name: ce_odoo
    depends_on:
      - db
    ports:
      - "8070:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo123
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    restart: unless-stopped

volumes:
  pgdata:
  odoo-data: